version: '3' # specify docker-compose version

services:
  database:
    build: ./db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db_data:/var/lib/mysql
      - .:/express-backend

  express: #name of the second service
    build: . # specify the directory of the Dockerfile
    volumes:
      - .:/express-backend/:rw
      - express_webmodule:/express-backend/node_modules
    ports:
      - "9999:3012" #specify ports forewarding 3012 is default in .env file
    restart: always
    links: 
      - database
    depends_on:
      - database
    environment:
      WAIT_HOSTS: ${DB_HOST}:${DB_PORT}
   
volumes:
  express_webmodule:
  db_data:
