version: '3' # specify docker-compose version

services:
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
      - .:/express-backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  express: #name of the second service
    build: . # specify the directory of the Dockerfile
    volumes:
      - .:/express-backend/:rw
      - express_webmodule:/express-backend/node_modules
    ports:
      - "9999:3012" #specify ports forewarding 3012 is default in .env file
    restart: always
    links:
      - database
    depends_on:
      - database
    # environment:
    #   WAIT_HOSTS: ${MYSQL_HOST}:${MYSQL_HOST}
   
volumes:
  express_webmodule:
  db_data:
